// seedCustomers.js

export const seedCustomers = [
  {
    name: "John Doe",
    email: "john@example.com",
    phone: "1234567890",
    address: "123 Main St",
    company: "Acme Corp",
    notes: "VIP customer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "9876543210",
    address: "456 Oak St",
    company: "Beta LLC",
    notes: "Loyal client",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Alice Brown",
    email: "alice@example.com",
    phone: "",
    address: "789 Pine St",
    company: "Gamma Inc",
    notes: "",
    image: null,
  },
  {
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "5551234567",
    address: "321 Maple Ave",
    company: "",
    notes: "Frequent buyer",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Eve Davis",
    email: "eve@example.com",
    phone: "",
    address: "654 Cedar Rd",
    company: "Delta Co",
    notes: "",
    image: null,
  },
  {
    name: "Frank Miller",
    email: "frank@example.com",
    phone: "4445556666",
    address: "987 Birch Blvd",
    company: "Omega Ltd",
    notes: "New customer",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    name: "Grace Lee",
    email: "grace@example.com",
    phone: "",
    address: "159 Elm St",
    company: "",
    notes: "",
    image: null,
  },
  {
    name: "Henry Wilson",
    email: "henry@example.com",
    phone: "7778889999",
    address: "753 Spruce Ln",
    company: "Zeta Solutions",
    notes: "Pending follow-up",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Ivy Martinez",
    email: "ivy@example.com",
    phone: "",
    address: "852 Willow Dr",
    company: "",
    notes: "",
    image: null,
  },
  {
    name: "Jack Taylor",
    email: "jack@example.com",
    phone: "2223334444",
    address: "951 Aspen Way",
    company: "Sigma Corp",
    notes: "",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    name: "Karen Anderson",
    email: "karen@example.com",
    phone: "",
    address: "357 Poplar St",
    company: "Theta LLC",
    notes: "Important client",
    image: null,
  },
  {
    name: "Leo Thomas",
    email: "leo@example.com",
    phone: "1112223333",
    address: "258 Chestnut Blvd",
    company: "",
    notes: "",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Mia White",
    email: "mia@example.com",
    phone: "",
    address: "147 Magnolia Ave",
    company: "Alpha Inc",
    notes: "",
    image: null,
  },
  {
    name: "Nathan Harris",
    email: "nathan@example.com",
    phone: "6667778888",
    address: "369 Cypress Rd",
    company: "",
    notes: "Frequent buyer",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "Olivia Scott",
    email: "olivia@example.com",
    phone: "",
    address: "753 Palm St",
    company: "",
    notes: "",
    image: null,
  },
  {
    name: "Paul King",
    email: "paul@example.com",
    phone: "9990001111",
    address: "852 Redwood Dr",
    company: "Beta Solutions",
    notes: "",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Quinn Baker",
    email: "quinn@example.com",
    phone: "",
    address: "951 Fir Ln",
    company: "",
    notes: "",
    image: null,
  },
];
